# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Name: WORK: HARDWARE-CONFIGURATION
# Type: Config (NixOS)
# Location: /hosts/work/
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
#  boot.kernelParams = [ "apple-gmux.force_igd=y" ];
  boot.kernelParams = [ ];
  boot.extraModulePackages = [ ];

  hardware.apple-t2.enableAppleSetOsLoader = true;

  services.logind = {
    lidSwitch = "lock";
    lidSwitchDocked = "lock";
    lidSwitchExternalPower = "lock";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/46ee2ea9-aec2-41cc-889d-4ac4cd0a8c9b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3973-071A";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/eb2ce297-dbc0-4abe-a789-66319a867146"; } ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
