# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/36e84c5d-6bcd-43e7-b841-d5aa95cc0fb4";
      fsType = "ext4";
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/29f3770a-5f96-4b34-8e0c-3f721f847487";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/73a30c65-c29a-4d6d-9e83-4cfb73320aec"; }
    ];
}