# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
      [ (modulesPath + "/profiles/qemu-guest.nix")
      ];

    boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "sd_mod" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/03d1fb57-0353-44d8-801e-e1eeacaed65a";
        fsType = "ext4";
      };

    fileSystems."/srv" =
      { device = "/dev/disk/by-uuid/cd86e8b4-dee5-4501-8235-14a53c6d4d43";
        fsType = "ext4";
      };

    swapDevices = [
      { device = "/dev/disk/by-uuid/12ffe00b-a1a0-4316-b8ab-78d4ad4212c0"; }
    ];
}