#!/usr/bin/env bash
function clamp {
	min=$1
	max=$2
	val=$3
	python -c "print(max($min, min($val, $max)))"
}

direction=$1
current=$2
if test "$direction" = "down"
then
	target=$(clamp 101 109 $(($current+1)))
	echo "jumping to $target"
	hyprctl dispatch workspace $target
elif test "$direction" = "up"
then
	target=$(clamp 101 109 $(($current-1)))
	echo "jumping to $target"
	hyprctl dispatch workspace $target
fi

bash ~/.config/eww/scripts/get-active-workspace-1 &
bash ~/.config/eww/scripts/get-active-workspace-2 & 
bash ~/.config/eww/scripts/get-active-workspace-3 &